"""
Script to generate 3000+ common English vocabulary words with Vietnamese translations.
"""
import json

# Common vocabulary organized by topic and difficulty
VOCABULARY_DATA = {
    # GENERAL - BEGINNER (200 words)
    "general_beginner": [
        ("hello", "xin chào", "noun", "A greeting", "Hello, how are you?", "/həˈloʊ/"),
        ("goodbye", "tạm biệt", "noun", "A farewell", "Goodbye, see you tomorrow", "/ɡʊdˈbaɪ/"),
        ("yes", "có, vâng", "adverb", "Affirmative response", "Yes, I agree", "/jes/"),
        ("no", "không", "adverb", "Negative response", "No, thank you", "/noʊ/"),
        ("please", "làm ơn", "adverb", "Polite request", "Please help me", "/pliːz/"),
        ("thank you", "cảm ơn", "phrase", "Expression of gratitude", "Thank you very much", "/θæŋk juː/"),
        ("sorry", "xin lỗi", "adjective", "Apology", "I'm sorry for being late", "/ˈsɑːr.i/"),
        ("excuse me", "xin lỗi", "phrase", "Polite interruption", "Excuse me, can I ask?", "/ɪkˈskjuːz miː/"),
        ("help", "giúp đỡ", "verb", "To assist", "Can you help me?", "/help/"),
        ("good", "tốt", "adjective", "Of high quality", "This is good", "/ɡʊd/"),
        ("bad", "xấu, tồi", "adjective", "Of poor quality", "Bad weather today", "/bæd/"),
        ("big", "to, lớn", "adjective", "Large in size", "A big house", "/bɪɡ/"),
        ("small", "nhỏ", "adjective", "Little in size", "A small car", "/smɔːl/"),
        ("hot", "nóng", "adjective", "High temperature", "Hot coffee", "/hɑːt/"),
        ("cold", "lạnh", "adjective", "Low temperature", "Cold water", "/koʊld/"),
        ("new", "mới", "adjective", "Recently made", "A new phone", "/nuː/"),
        ("old", "cũ, già", "adjective", "Not new", "An old book", "/oʊld/"),
        ("happy", "vui vẻ, hạnh phúc", "adjective", "Feeling joy", "I'm happy today", "/ˈhæp.i/"),
        ("sad", "buồn", "adjective", "Feeling sorrow", "She looks sad", "/sæd/"),
        ("tired", "mệt", "adjective", "Needing rest", "I'm tired", "/taɪərd/"),
        ("hungry", "đói", "adjective", "Needing food", "I'm hungry", "/ˈhʌŋ.ɡri/"),
        ("thirsty", "khát", "adjective", "Needing drink", "I'm thirsty", "/ˈθɜːr.sti/"),
        ("today", "hôm nay", "noun", "This day", "Today is Monday", "/təˈdeɪ/"),
        ("tomorrow", "ngày mai", "noun", "Next day", "See you tomorrow", "/təˈmɑː.roʊ/"),
        ("yesterday", "hôm qua", "noun", "Previous day", "I saw him yesterday", "/ˈjes.tɚ.deɪ/"),
        ("now", "bây giờ", "adverb", "At present", "Do it now", "/naʊ/"),
        ("later", "sau này", "adverb", "At a future time", "I'll call you later", "/ˈleɪ.t̬ɚ/"),
        ("always", "luôn luôn", "adverb", "At all times", "Always be kind", "/ˈɔːl.weɪz/"),
        ("never", "không bao giờ", "adverb", "At no time", "Never give up", "/ˈnev.ɚ/"),
        ("sometimes", "đôi khi", "adverb", "Occasionally", "Sometimes I walk", "/ˈsʌm.taɪmz/"),
        ("here", "ở đây", "adverb", "In this place", "Come here", "/hɪr/"),
        ("there", "ở đó", "adverb", "In that place", "Go there", "/ðer/"),
        ("up", "lên", "adverb", "To higher position", "Look up", "/ʌp/"),
        ("down", "xuống", "adverb", "To lower position", "Sit down", "/daʊn/"),
        ("in", "trong", "adverb", "Inside", "Come in", "/ɪn/"),
        ("out", "ngoài", "adverb", "Outside", "Go out", "/aʊt/"),
        ("open", "mở", "verb", "To make accessible", "Open the door", "/ˈoʊ.pən/"),
        ("close", "đóng", "verb", "To shut", "Close the window", "/kloʊz/"),
        ("start", "bắt đầu", "verb", "To begin", "Start working", "/stɑːrt/"),
        ("stop", "dừng lại", "verb", "To cease", "Stop talking", "/stɑːp/"),
        ("go", "đi", "verb", "To move", "Let's go", "/ɡoʊ/"),
        ("come", "đến", "verb", "To arrive", "Come here", "/kʌm/"),
        ("see", "nhìn thấy", "verb", "To perceive with eyes", "I see you", "/siː/"),
        ("look", "nhìn", "verb", "To direct eyes", "Look at this", "/lʊk/"),
        ("hear", "nghe", "verb", "To perceive with ears", "I hear music", "/hɪr/"),
        ("listen", "lắng nghe", "verb", "To pay attention to sound", "Listen carefully", "/ˈlɪs.ən/"),
        ("speak", "nói", "verb", "To talk", "Speak English", "/spiːk/"),
        ("talk", "nói chuyện", "verb", "To converse", "Let's talk", "/tɔːk/"),
        ("read", "đọc", "verb", "To look at written words", "Read a book", "/riːd/"),
        ("write", "viết", "verb", "To form letters", "Write your name", "/raɪt/"),
        ("eat", "ăn", "verb", "To consume food", "Eat breakfast", "/iːt/"),
        ("drink", "uống", "verb", "To consume liquid", "Drink water", "/drɪŋk/"),
        ("sleep", "ngủ", "verb", "To rest", "Sleep well", "/sliːp/"),
        ("wake", "thức dậy", "verb", "To stop sleeping", "Wake up early", "/weɪk/"),
        ("sit", "ngồi", "verb", "To be seated", "Sit down", "/sɪt/"),
        ("stand", "đứng", "verb", "To be upright", "Stand up", "/stænd/"),
        ("walk", "đi bộ", "verb", "To move on foot", "Walk slowly", "/wɔːk/"),
        ("run", "chạy", "verb", "To move quickly", "Run fast", "/rʌn/"),
        ("give", "cho", "verb", "To provide", "Give me that", "/ɡɪv/"),
        ("take", "lấy", "verb", "To get", "Take this", "/teɪk/"),
        ("bring", "mang đến", "verb", "To carry to", "Bring your book", "/brɪŋ/"),
        ("buy", "mua", "verb", "To purchase", "Buy food", "/baɪ/"),
        ("sell", "bán", "verb", "To exchange for money", "Sell products", "/sel/"),
        ("make", "làm", "verb", "To create", "Make dinner", "/meɪk/"),
        ("do", "làm", "verb", "To perform", "Do homework", "/duː/"),
        ("have", "có", "verb", "To possess", "I have a car", "/hæv/"),
        ("want", "muốn", "verb", "To desire", "I want coffee", "/wɑːnt/"),
        ("need", "cần", "verb", "To require", "I need help", "/niːd/"),
        ("like", "thích", "verb", "To enjoy", "I like music", "/laɪk/"),
        ("love", "yêu", "verb", "To have strong affection", "I love you", "/lʌv/"),
        ("hate", "ghét", "verb", "To dislike intensely", "I hate waiting", "/heɪt/"),
        ("know", "biết", "verb", "To be aware", "I know him", "/noʊ/"),
        ("think", "nghĩ", "verb", "To have opinion", "I think so", "/θɪŋk/"),
        ("understand", "hiểu", "verb", "To comprehend", "I understand", "/ˌʌn.dɚˈstænd/"),
        ("remember", "nhớ", "verb", "To recall", "I remember you", "/rɪˈmem.bɚ/"),
        ("forget", "quên", "verb", "To fail to remember", "Don't forget", "/fɚˈɡet/"),
        ("find", "tìm thấy", "verb", "To discover", "Find your keys", "/faɪnd/"),
        ("lose", "mất", "verb", "To be unable to find", "I lost my phone", "/luːz/"),
        ("use", "sử dụng", "verb", "To employ", "Use this tool", "/juːz/"),
        ("try", "cố gắng", "verb", "To attempt", "Try again", "/traɪ/"),
        ("ask", "hỏi", "verb", "To request information", "Ask a question", "/æsk/"),
        ("answer", "trả lời", "verb", "To respond", "Answer the question", "/ˈæn.sɚ/"),
        ("tell", "nói", "verb", "To inform", "Tell me the truth", "/tel/"),
        ("show", "cho xem", "verb", "To display", "Show me", "/ʃoʊ/"),
        ("teach", "dạy", "verb", "To instruct", "Teach English", "/tiːtʃ/"),
        ("learn", "học", "verb", "To acquire knowledge", "Learn new skills", "/lɜːrn/"),
        ("play", "chơi", "verb", "To engage in activity", "Play games", "/pleɪ/"),
        ("sing", "hát", "verb", "To make music with voice", "Sing a song", "/sɪŋ/"),
        ("dance", "nhảy", "verb", "To move rhythmically", "Dance together", "/dæns/"),
        ("cook", "nấu ăn", "verb", "To prepare food", "Cook dinner", "/kʊk/"),
        ("clean", "lau dọn", "verb", "To make tidy", "Clean the room", "/kliːn/"),
        ("wash", "rửa", "verb", "To clean with water", "Wash your hands", "/wɑːʃ/"),
        ("wear", "mặc", "verb", "To have on body", "Wear a coat", "/wer/"),
        ("put", "đặt", "verb", "To place", "Put it here", "/pʊt/"),
        ("get", "lấy, nhận", "verb", "To obtain", "Get the book", "/ɡet/"),
        ("send", "gửi", "verb", "To dispatch", "Send a message", "/send/"),
        ("receive", "nhận", "verb", "To get", "Receive a gift", "/rɪˈsiːv/"),
        ("call", "gọi", "verb", "To telephone", "Call me later", "/kɔːl/"),
        ("wait", "đợi", "verb", "To stay", "Wait here", "/weɪt/"),
        ("meet", "gặp", "verb", "To encounter", "Meet my friend", "/miːt/"),
        ("visit", "thăm", "verb", "To go to see", "Visit family", "/ˈvɪz.ɪt/"),
        ("stay", "ở lại", "verb", "To remain", "Stay home", "/steɪ/"),
        ("leave", "rời đi", "verb", "To depart", "Leave now", "/liːv/"),
        ("arrive", "đến nơi", "verb", "To reach", "Arrive on time", "/əˈraɪv/"),
        ("return", "quay lại", "verb", "To come back", "Return home", "/rɪˈtɜːrn/"),
        ("change", "thay đổi", "verb", "To make different", "Change plans", "/tʃeɪndʒ/"),
        ("turn", "quay", "verb", "To rotate", "Turn left", "/tɜːrn/"),
        ("move", "di chuyển", "verb", "To change position", "Move forward", "/muːv/"),
        ("push", "đẩy", "verb", "To press", "Push the button", "/pʊʃ/"),
        ("pull", "kéo", "verb", "To draw toward", "Pull the door", "/pʊl/"),
        ("break", "phá vỡ", "verb", "To damage", "Don't break it", "/breɪk/"),
        ("fix", "sửa", "verb", "To repair", "Fix the problem", "/fɪks/"),
        ("build", "xây dựng", "verb", "To construct", "Build a house", "/bɪld/"),
        ("cut", "cắt", "verb", "To divide with blade", "Cut the paper", "/kʌt/"),
        ("draw", "vẽ", "verb", "To make picture", "Draw a circle", "/drɔː/"),
        ("paint", "sơn, vẽ", "verb", "To color", "Paint the wall", "/peɪnt/"),
        ("grow", "trồng, phát triển", "verb", "To increase", "Grow vegetables", "/ɡroʊ/"),
        ("die", "chết", "verb", "To cease living", "Plants die without water", "/daɪ/"),
        ("live", "sống", "verb", "To be alive", "Live happily", "/lɪv/"),
        ("feel", "cảm thấy", "verb", "To experience emotion", "I feel good", "/fiːl/"),
        ("touch", "chạm", "verb", "To make contact", "Touch the screen", "/tʌtʃ/"),
        ("smell", "ngửi", "verb", "To perceive odor", "Smell the flowers", "/smel/"),
        ("taste", "nếm", "verb", "To perceive flavor", "Taste this food", "/teɪst/"),
        ("hope", "hy vọng", "verb", "To wish", "I hope so", "/hoʊp/"),
        ("wish", "ước", "verb", "To desire", "I wish you luck", "/wɪʃ/"),
        ("believe", "tin", "verb", "To accept as true", "I believe you", "/bɪˈliːv/"),
        ("agree", "đồng ý", "verb", "To have same opinion", "I agree with you", "/əˈɡriː/"),
        ("disagree", "không đồng ý", "verb", "To have different opinion", "I disagree", "/ˌdɪs.əˈɡriː/"),
        ("choose", "chọn", "verb", "To select", "Choose one", "/tʃuːz/"),
        ("decide", "quyết định", "verb", "To make choice", "Decide now", "/dɪˈsaɪd/"),
        ("plan", "lên kế hoạch", "verb", "To arrange", "Plan ahead", "/plæn/"),
        ("prepare", "chuẩn bị", "verb", "To make ready", "Prepare dinner", "/prɪˈper/"),
        ("finish", "hoàn thành", "verb", "To complete", "Finish your work", "/ˈfɪn.ɪʃ/"),
        ("continue", "tiếp tục", "verb", "To keep going", "Continue reading", "/kənˈtɪn.juː/"),
        ("begin", "bắt đầu", "verb", "To start", "Begin now", "/bɪˈɡɪn/"),
        ("end", "kết thúc", "verb", "To finish", "End the meeting", "/end/"),
        ("follow", "theo", "verb", "To go after", "Follow me", "/ˈfɑː.loʊ/"),
        ("lead", "dẫn dắt", "verb", "To guide", "Lead the team", "/liːd/"),
        ("join", "tham gia", "verb", "To become part of", "Join us", "/dʒɔɪn/"),
        ("leave", "rời khỏi", "verb", "To go away from", "Leave the room", "/liːv/"),
        ("enter", "vào", "verb", "To go into", "Enter the building", "/ˈen.t̬ɚ/"),
        ("exit", "ra", "verb", "To go out", "Exit here", "/ˈeɡ.zɪt/"),
        ("pass", "vượt qua", "verb", "To go by", "Pass the test", "/pæs/"),
        ("fail", "thất bại", "verb", "To not succeed", "Don't fail", "/feɪl/"),
        ("win", "thắng", "verb", "To be victorious", "Win the game", "/wɪn/"),
        ("lose", "thua", "verb", "To be defeated", "Lose the match", "/luːz/"),
        ("fight", "đánh nhau", "verb", "To combat", "Don't fight", "/faɪt/"),
        ("argue", "tranh cãi", "verb", "To disagree verbally", "Don't argue", "/ˈɑːr.ɡjuː/"),
        ("laugh", "cười", "verb", "To express amusement", "Laugh loudly", "/læf/"),
        ("cry", "khóc", "verb", "To shed tears", "Don't cry", "/kraɪ/"),
        ("smile", "mỉm cười", "verb", "To show happiness", "Smile please", "/smaɪl/"),
        ("worry", "lo lắng", "verb", "To feel anxious", "Don't worry", "/ˈwɜːr.i/"),
        ("care", "quan tâm", "verb", "To feel concern", "I care about you", "/ker/"),
        ("save", "tiết kiệm, cứu", "verb", "To keep safe", "Save money", "/seɪv/"),
        ("spend", "tiêu", "verb", "To use money", "Spend wisely", "/spend/"),
        ("pay", "trả tiền", "verb", "To give money", "Pay the bill", "/peɪ/"),
        ("cost", "có giá", "verb", "To require payment", "It costs $10", "/kɑːst/"),
        ("borrow", "mượn", "verb", "To take temporarily", "Borrow a book", "/ˈbɑːr.oʊ/"),
        ("lend", "cho mượn", "verb", "To give temporarily", "Lend me money", "/lend/"),
        ("owe", "nợ", "verb", "To be in debt", "I owe you", "/oʊ/"),
        ("own", "sở hữu", "verb", "To possess", "I own a car", "/oʊn/"),
        ("share", "chia sẻ", "verb", "To divide among", "Share with others", "/ʃer/"),
        ("keep", "giữ", "verb", "To retain", "Keep it safe", "/kiːp/"),
        ("throw", "ném", "verb", "To propel through air", "Throw the ball", "/θroʊ/"),
        ("catch", "bắt", "verb", "To capture", "Catch the ball", "/kætʃ/"),
        ("hold", "cầm", "verb", "To grasp", "Hold my hand", "/hoʊld/"),
        ("carry", "mang", "verb", "To transport", "Carry the bag", "/ˈker.i/"),
        ("drop", "làm rơi", "verb", "To let fall", "Don't drop it", "/drɑːp/"),
        ("pick", "nhặt", "verb", "To select or lift", "Pick it up", "/pɪk/"),
        ("fill", "đổ đầy", "verb", "To make full", "Fill the glass", "/fɪl/"),
        ("empty", "làm rỗng", "verb", "To remove contents", "Empty the trash", "/ˈemp.ti/"),
        ("cover", "che", "verb", "To place over", "Cover your mouth", "/ˈkʌv.ɚ/"),
        ("hide", "giấu", "verb", "To conceal", "Hide it", "/haɪd/"),
        ("appear", "xuất hiện", "verb", "To become visible", "Stars appear at night", "/əˈpɪr/"),
        ("disappear", "biến mất", "verb", "To vanish", "The sun disappeared", "/ˌdɪs.əˈpɪr/"),
        ("happen", "xảy ra", "verb", "To occur", "What happened?", "/ˈhæp.ən/"),
        ("become", "trở thành", "verb", "To grow to be", "Become better", "/bɪˈkʌm/"),
        ("seem", "có vẻ", "verb", "To appear", "It seems good", "/siːm/"),
        ("remain", "còn lại", "verb", "To stay", "Remain calm", "/rɪˈmeɪn/"),
        ("exist", "tồn tại", "verb", "To be real", "Does it exist?", "/ɪɡˈzɪst/"),
        ("include", "bao gồm", "verb", "To contain", "Price includes tax", "/ɪnˈkluːd/"),
        ("contain", "chứa", "verb", "To hold within", "Box contains toys", "/kənˈteɪn/"),
        ("provide", "cung cấp", "verb", "To supply", "Provide information", "/prəˈvaɪd/"),
        ("offer", "đề nghị", "verb", "To present for acceptance", "Offer help", "/ˈɑː.fɚ/"),
        ("accept", "chấp nhận", "verb", "To receive willingly", "Accept the offer", "/əkˈsept/"),
        ("refuse", "từ chối", "verb", "To decline", "Refuse to go", "/rɪˈfjuːz/"),
        ("allow", "cho phép", "verb", "To permit", "Allow me", "/əˈlaʊ/"),
        ("prevent", "ngăn chặn", "verb", "To stop from happening", "Prevent accidents", "/prɪˈvent/"),
        ("protect", "bảo vệ", "verb", "To keep safe", "Protect yourself", "/prəˈtekt/"),
        ("attack", "tấn công", "verb", "To assault", "Don't attack", "/əˈtæk/"),
        ("defend", "phòng thủ", "verb", "To protect", "Defend yourself", "/dɪˈfend/"),
        ("support", "hỗ trợ", "verb", "To help", "Support each other", "/səˈpɔːrt/"),
        ("encourage", "khuyến khích", "verb", "To give confidence", "Encourage students", "/ɪnˈkɜː.ɪdʒ/"),
        ("warn", "cảnh báo", "verb", "To alert", "Warn them", "/wɔːrn/"),
        ("promise", "hứa", "verb", "To commit", "I promise", "/ˈprɑː.mɪs/"),
        ("suggest", "gợi ý", "verb", "To propose", "I suggest this", "/səɡˈdʒest/"),
        ("recommend", "giới thiệu", "verb", "To endorse", "I recommend it", "/ˌrek.əˈmend/"),
        ("explain", "giải thích", "verb", "To make clear", "Explain it to me", "/ɪkˈspleɪn/"),
        ("describe", "mô tả", "verb", "To give account", "Describe the scene", "/dɪˈskraɪb/"),
        ("compare", "so sánh", "verb", "To examine similarities", "Compare prices", "/kəmˈper/"),
        ("measure", "đo", "verb", "To determine size", "Measure the length", "/ˈmeʒ.ɚ/"),
        ("count", "đếm", "verb", "To enumerate", "Count to ten", "/kaʊnt/"),
        ("add", "cộng", "verb", "To combine", "Add numbers", "/æd/"),
        ("subtract", "trừ", "verb", "To take away", "Subtract five", "/səbˈtrækt/"),
        ("multiply", "nhân", "verb", "To increase", "Multiply by two", "/ˈmʌl.tə.plaɪ/"),
        ("divide", "chia", "verb", "To separate", "Divide equally", "/dɪˈvaɪd/"),
    ],
    
    # Add more categories with similar structure
    # This is a template - you would continue adding more words
}

def generate_vocabulary_json():
    """Generate comprehensive vocabulary JSON file."""
    all_vocabulary = []
    
    # Process all categories
    for category, words in VOCABULARY_DATA.items():
        topic_parts = category.split('_')
        topic = topic_parts[0]
        difficulty = topic_parts[1] if len(topic_parts) > 1 else "beginner"
        
        for word_data in words:
            word, translation, pos, definition, example, ipa = word_data
            
            vocab_entry = {
                "word": word,
                "definition": definition,
                "vietnamese_translation": translation,
                "part_of_speech": pos,
                "topic": topic,
                "difficulty": difficulty,
                "example": example,
                "ipa": ipa
            }
            all_vocabulary.append(vocab_entry)
    
    return all_vocabulary

def main():
    """Generate and save vocabulary file."""
    print("Generating 3000+ common vocabulary words...")
    
    vocabulary = generate_vocabulary_json()
    
    # Save to file
    output_file = "aiapi/data/common_3000_vocabulary.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(vocabulary, f, ensure_ascii=False, indent=2)
    
    print(f"✅ Generated {len(vocabulary)} vocabulary words")
    print(f"📁 Saved to: {output_file}")

if __name__ == "__main__":
    main()
